### ISSUE TITLE
Numbering change suggestion

### ISSUE THREAD

**Issue by emg110** [algorandfoundation/technical-adoption-committee#5]
For easier tracking and reading may I suggest the numbering on the chart to change to ARC numbers instead of 1,2,3,..! This way one can immediately spot the status of each ARC by one look at the radar visuals!

**Comment by ehanoc** [comment]
I'm not sure that is easy to do with the current script we use to generate the radar. But removing the enumeration itself it's easy enough. That should remove the confusion. What do you think?

**Comment by emg110** [comment]
Absolutely right! I agree!
